sudo: required
dist: focal
matrix:
  include:
  - os: linux
    language: python
    python: '3.6'
  - os: linux
    language: python
    arch: arm64
    python: '3.6'

before install:
  - python -m pip install --upgrade pip setuptools
  - pip install -r requirements.txt
    
install:
  - python setup.py build_ext --inplace
  - python setup.py sdist --formats=gztar
  
script:
  - python -m pytest --pyargs srsly
